[workspace]
resolver = "3"

members = [
    "balius-server",
    "balius-worker-builder",
    "sundae-strategies",
    "workers/*",
]

[workspace.dependencies]
balius-sdk = { git = "https://github.com/txpipe/balius.git" }
